# Generated by Django 2.0.6 on 2018-06-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180628_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='isbn',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='jan',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='local_barcode',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_keyword',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_tag',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mpn',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_tags',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='related_product',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='upc',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
